services:

  myapp:
    image: sample-app:dev
    volumes:
      # монтируем исходники чтобы изменения отражались в контейнере
      - ./src:/app/src
      # монтируем package.json чтобы не нужно было пересобирать образ если мы потрогали скрипты
      - ./package.json:/app/package.json

  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sample
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: hello
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: